import type { CompletedCourse } from '../courses'

export const INITIAL_COMPLETED_COURSES: CompletedCourse[] = [
  {
    id: 'INF4220',
    title: 'Machine Learning',
    ects: 9,
    masterCat: 'TECH',
    grade: 1.7,
    semester: 'WS 2025/26',
  },
  {
    id: 'INF4601',
    title: 'Formal Methods',
    ects: 6,
    masterCat: 'THEO',
    grade: 1.3,
    semester: 'WS 2025/26',
  },
  {
    id: 'INF4810',
    title: 'Cryptography',
    ects: 6,
    masterCat: 'THEO',
    grade: 2,
    semester: 'WS 2025/26',
  },
  {
    id: 'INF4952',
    title: 'Database Systems',
    ects: 6,
    masterCat: 'PRAK',
    grade: 2.7,
    semester: 'SS 2025',
  },
  {
    id: 'INF4700',
    title: 'Natural Language Processing',
    ects: 6,
    masterCat: 'INFO',
    grade: 1.7,
    semester: 'SS 2025',
  },
  {
    id: 'INF4450',
    title: 'Computer Vision',
    ects: 9,
    masterCat: 'TECH',
    grade: 1.3,
    semester: 'SS 2025',
  },
  {
    id: 'INF4010',
    title: 'Mathematics for Machine Learning',
    ects: 9,
    masterCat: 'BASIS',
    grade: 1,
    semester: 'WS 2024/25',
  },
  {
    id: 'INF4020',
    title: 'Introduction to AI',
    ects: 6,
    masterCat: 'BASIS',
    grade: 2.3,
    semester: 'WS 2024/25',
  },
]
