"""Seed the `loadtest-*` accounts used by the concurrent-user stress test.

    py backend/scripts/seed_load_test_users.py --count 20            # dry run
    py backend/scripts/seed_load_test_users.py --count 20 --apply    # write to D1

The password is never stored in the repo: set LOADTEST_PASSWORD in the
environment before running. The same value must be passed to the k6 harness
(see load-test/README.md).

Why seed through SQL instead of POSTing /api/auth/register:
AUTH_REGISTRATION_POLICY in backend/src/services/request_rate_limit.py allows 5
registrations per hour per client IP, so creating 20 accounts through the API
from one machine would take four hours.

The rows this writes mirror what register_user() in
backend/src/services/authentication.py produces:

  * user_auth  — username/email/password_hash/password_salt. The hash format is
    PBKDF2-HMAC-SHA256 at PASSWORD_PBKDF2_ITERATIONS, hex-encoded, exactly as
    _hash_password() computes it. If that constant ever changes, logins for
    these accounts break until this script is re-run.
  * user_state — display name plus the supported PO 2021 study program and its
    default regulation version, resolved by subselect. login_user() would
    backfill a bare user_state row on its own, but seeding the study program
    matters: without it /api/me/progress short-circuits and the stress test
    would exercise a much cheaper query path than a real account does.

user_progress is left to ensure_user_progress() on first login.

Re-running is safe: user_auth rows are upserted (so a password change is just a
re-run) and user_state rows use INSERT OR IGNORE so an account that has since
accumulated planner data is never reset.

These accounts are intentionally retained after a test run, like the
debug-onboarding-* accounts described in CLAUDE.md. Exclude them from user
counts.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import secrets
import subprocess
import sys
import time
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_OUT_SQL = ROOT_DIR / "data" / "seed_load_test_users.sql"
DEFAULT_DB_NAME = "studyplanner-db"
DEFAULT_COUNT = 20
DEFAULT_ACCOUNT_TEMPLATE = "loadtest-{index:02d}@example.com"

# Must stay in sync with PASSWORD_PBKDF2_ITERATIONS in
# backend/src/services/authentication.py — a mismatch produces accounts that
# exist but can never log in.
PASSWORD_PBKDF2_ITERATIONS = 310_000

# Mirrors SUPPORTED_REGULATION_SOURCE_STATUS / SUPPORTED_REGULATION_PO_VERSION.
SUPPORTED_SOURCE_STATUS = "official"
SUPPORTED_PO_VERSION = "2021"


def hash_password(password: str, salt_hex: str) -> str:
    """Hash exactly as authentication._hash_password does."""
    password_hash = hashlib.pbkdf2_hmac(
        "sha256",
        password.encode("utf-8"),
        bytes.fromhex(salt_hex),
        PASSWORD_PBKDF2_ITERATIONS,
    )
    return password_hash.hex()


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_account_usernames(count: int, template: str) -> list[str]:
    if count < 1:
        raise ValueError("count must be at least 1")
    return [template.format(index=index) for index in range(1, count + 1)]


def build_seed_sql(usernames: list[str], password: str, now_unix: int) -> str:
    """Return idempotent SQL creating one credential + state row per account."""
    statements: list[str] = [
        "-- Generated by backend/scripts/seed_load_test_users.py — do not edit by hand.",
        "-- Stress-test accounts; see load-test/README.md.",
        "",
    ]

    for username in usernames:
        salt_hex = secrets.token_hex(16)
        password_hash = hash_password(password, salt_hex)
        quoted_username = sql_quote(username)
        statements.append(
            "INSERT INTO user_auth ("
            "username, email, password_hash, password_salt, created_at_unix, updated_at_unix"
            ") VALUES ("
            f"{quoted_username}, {quoted_username}, "
            f"{sql_quote(password_hash)}, {sql_quote(salt_hex)}, {now_unix}, {now_unix}"
            ") ON CONFLICT(username) DO UPDATE SET "
            "password_hash = excluded.password_hash, "
            "password_salt = excluded.password_salt, "
            "updated_at_unix = excluded.updated_at_unix;"
        )

    statements.append("")

    for username in usernames:
        quoted_username = sql_quote(username)
        display_name = sql_quote(username.split("@", 1)[0])
        statements.append(
            "INSERT OR IGNORE INTO user_state ("
            "username, display_name, created_at_unix, updated_at_unix"
            f") VALUES ({quoted_username}, {display_name}, {now_unix}, {now_unix});"
        )

    statements.append("")

    # The study program is attached in two follow-up UPDATEs rather than inline
    # in each INSERT, so each subselect is written once instead of once per
    # account. Both are guarded by `IS NULL`, so re-running never overwrites a
    # program an account has since been given.
    username_list = ", ".join(sql_quote(username) for username in usernames)
    official = sql_quote(SUPPORTED_SOURCE_STATUS)
    po_version = sql_quote(SUPPORTED_PO_VERSION)

    # Resolved by subselect rather than a hardcoded id so this keeps working
    # after a catalog re-seed renumbers study_programs.
    statements.append(
        "UPDATE user_state SET study_program_id = ("
        "SELECT sp.id FROM study_programs AS sp"
        " JOIN study_program_regulation_versions AS sprv"
        " ON sprv.study_program_id = sp.id AND sprv.is_default = 1"
        " JOIN regulation_versions AS rv ON rv.id = sprv.regulation_version_id"
        f" WHERE sp.source_status = {official} AND sp.po_version = {po_version}"
        f" AND rv.source_status = {official} AND rv.version_label = {po_version}"
        " ORDER BY sp.id LIMIT 1"
        f") WHERE username IN ({username_list}) AND study_program_id IS NULL;"
    )
    statements.append(
        "UPDATE user_state SET regulation_version_id = ("
        "SELECT sprv.regulation_version_id FROM study_program_regulation_versions AS sprv"
        " JOIN regulation_versions AS rv ON rv.id = sprv.regulation_version_id"
        " WHERE sprv.study_program_id = user_state.study_program_id"
        " AND sprv.is_default = 1"
        f" AND rv.source_status = {official} AND rv.version_label = {po_version}"
        " LIMIT 1"
        f") WHERE username IN ({username_list}) AND regulation_version_id IS NULL;"
    )

    statements.append("")
    return "\n".join(statements)


def wrangler_d1_execute_file(db_name: str, sql_path: Path, *, remote: bool) -> None:
    target = "--remote" if remote else "--local"
    print(f"[wrangler] executing {sql_path} on '{db_name}' {target} ...")
    result = subprocess.run(
        ["wrangler", "d1", "execute", db_name, target, "--file", str(sql_path)],
        cwd=ROOT_DIR, text=True, shell=True,
        stdin=subprocess.DEVNULL, encoding="utf-8", errors="replace",
    )
    if result.returncode != 0:
        raise SystemExit(f"wrangler d1 execute failed (exit {result.returncode})")


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--count", type=int, default=DEFAULT_COUNT,
                        help=f"Number of accounts to seed (default {DEFAULT_COUNT}).")
    parser.add_argument("--account-template", default=DEFAULT_ACCOUNT_TEMPLATE,
                        help="Username/email template; must contain {index}.")
    parser.add_argument("--out-sql", type=Path, default=DEFAULT_OUT_SQL,
                        help="Where to write the generated SQL.")
    parser.add_argument("--db-name", default=DEFAULT_DB_NAME,
                        help=f"D1 database name (default {DEFAULT_DB_NAME}).")
    parser.add_argument("--local", action="store_true",
                        help="Target the local D1 simulator instead of --remote.")
    parser.add_argument("--apply", action="store_true",
                        help="Actually execute the SQL. Without it the script only writes the file.")
    return parser.parse_args()


def main() -> None:
    args = parse_arguments()

    password = os.environ.get("LOADTEST_PASSWORD", "").strip()
    if not password:
        raise SystemExit(
            "LOADTEST_PASSWORD is not set. Choose a throwaway password and export it, "
            "e.g. $env:LOADTEST_PASSWORD = '<value>' — it is never stored in the repo."
        )

    usernames = build_account_usernames(args.count, args.account_template)
    print(f"[seed] hashing {len(usernames)} passwords at {PASSWORD_PBKDF2_ITERATIONS:,} PBKDF2 iterations ...")
    seed_sql = build_seed_sql(usernames, password, int(time.time()))

    args.out_sql.parent.mkdir(parents=True, exist_ok=True)
    args.out_sql.write_text(seed_sql, encoding="utf-8")
    print(f"[seed] wrote {args.out_sql} ({len(usernames)} accounts: {usernames[0]} .. {usernames[-1]})")

    if not args.apply:
        target = "--local" if args.local else "--remote"
        print("[seed] dry run — nothing executed. To apply:")
        print(f"  wrangler d1 execute {args.db_name} {target} --file {args.out_sql}")
        return

    wrangler_d1_execute_file(args.db_name, args.out_sql, remote=not args.local)
    print("[seed] done. Verify with:")
    print(f"  wrangler d1 execute {args.db_name} {'--local' if args.local else '--remote'} "
          f"--command \"SELECT COUNT(*) FROM user_auth WHERE username LIKE 'loadtest-%'\"")


if __name__ == "__main__":
    sys.exit(main())
